const Citys=[
        {"id":1,
          "city": "Casablanca", 
          "lat": "33.5992", 
          "lng": "-7.6200", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "admin", 
          "population": "4370000", 
          "population_proper": "4370000"
        }, 
        {"id":2,
          "city": "El Kelaa des Srarhna", 
          "lat": "32.0500", 
          "lng": "-7.4000", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "1450021", 
          "population_proper": "1450021"
        }, 
        {"id":3,
          "city": "Fès", 
          "lat": "34.0433", 
          "lng": "-5.0033", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "admin", 
          "population": "1112072", 
          "population_proper": "1112072"
        }, 
        {"id":4,
          "city": "Tangier", 
          "lat": "35.7767", 
          "lng": "-5.8039", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "admin", 
          "population": "947952", 
          "population_proper": "947952"
        }, 
        {"id":5,
          "city": "Marrakech", 
          "lat": "31.6295", 
          "lng": "-7.9811", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "admin", 
          "population": "928850", 
          "population_proper": "928850"
        }, 
        {"id":6,
          "city": "Sale", 
          "lat": "34.0500", 
          "lng": "-6.8167", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "850403", 
          "population_proper": "850403"
        }, 
        {"id":7,
          "city": "Rabat", 
          "lat": "34.0253", 
          "lng": "-6.8361", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "primary", 
          "population": "572717", 
          "population_proper": "572717"
        }, 
        {"id":8,
          "city": "Meknès", 
          "lat": "33.8833", 
          "lng": "-5.5500", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "520428", 
          "population_proper": "520428"
        }, 
        {"id":9,
          "city": "Kenitra", 
          "lat": "34.2500", 
          "lng": "-6.5833", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "431282", 
          "population_proper": "431282"
        }, 
        {"id":10,
          "city": "Agadir", 
          "lat": "30.4167", 
          "lng": "-9.5833", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "admin", 
          "population": "421844", 
          "population_proper": "421844"
        }, 
        {"id":11,
          "city": "Oujda-Angad", 
          "lat": "34.6900", 
          "lng": "-1.9100", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Oriental", 
          "capital": "admin", 
          "population": "409391", 
          "population_proper": "405253"
        }, 
        {"id":12,
          "city": "Tétouan", 
          "lat": "35.5667", 
          "lng": "-5.3667", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "380787", 
          "population_proper": "380787"
        }, 
        {"id":14,
          "city": "Taourirt", 
          "lat": "34.4100", 
          "lng": "-2.8900", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Oriental", 
          "capital": "", 
          "population": "321876", 
          "population_proper": "321876"
        }, 
        {"id":15,
          "city": "Temara", 
          "lat": "33.9234", 
          "lng": "-6.9076", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "313510", 
          "population_proper": "313510"
        }, 
        {"id":16,
          "city": "Safi", 
          "lat": "32.2833", 
          "lng": "-9.2333", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "308508", 
          "population_proper": "308508"
        }, 
        {"id":17,
          "city": "Laâyoune", 
          "lat": "27.1500", 
          "lng": "-13.2000", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "", 
          "capital": "", 
          "population": "217732", 
          "population_proper": "217732"
        }, 
        {"id":18,
          "city": "Mohammedia", 
          "lat": "33.6833", 
          "lng": "-7.3833", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "208612", 
          "population_proper": "208612"
        }, 
        {"id":19,
          "city": "Kouribga", 
          "lat": "32.8800", 
          "lng": "-6.9000", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "196196", 
          "population_proper": "196196"
        }, 
        {"id":20,
          "city": "Béni Mellal", 
          "lat": "32.3394", 
          "lng": "-6.3608", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "admin", 
          "population": "192676", 
          "population_proper": "192676"
        }, 
        {"id":21,
          "city": "El Jadid", 
          "lat": "33.2566", 
          "lng": "-8.5025", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "180470", 
          "population_proper": "147549"
        }, 
        {"id":22,
          "city": "Ait Melloul", 
          "lat": "30.3342", 
          "lng": "-9.4972", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "", 
          "population": "171847", 
          "population_proper": "171847"
        }, 
        {"id":23,
          "city": "Nador", 
          "lat": "35.1667", 
          "lng": "-2.9333", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Oriental", 
          "capital": "", 
          "population": "161726", 
          "population_proper": "161726"
        }, 
        {"id":24,
          "city": "Taza", 
          "lat": "34.2144", 
          "lng": "-4.0088", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "148456", 
          "population_proper": "148456"
        }, 
        {"id":25,
          "city": "Settat", 
          "lat": "33.0023", 
          "lng": "-7.6198", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "142250", 
          "population_proper": "142250"
        }, 
        {"id":26,
          "city": "Barrechid", 
          "lat": "33.2700", 
          "lng": "-7.5872", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "136634", 
          "population_proper": "136634"
        }, 
        {"id":27,
          "city": "Al Khmissat", 
          "lat": "33.8100", 
          "lng": "-6.0600", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "131542", 
          "population_proper": "131542"
        }, 
        {"id":28,
          "city": "Inezgane", 
          "lat": "30.3658", 
          "lng": "-9.5381", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "", 
          "population": "130333", 
          "population_proper": "130333"
        }, 
        {"id":29,
          "city": "Ksar El Kebir", 
          "lat": "35.0000", 
          "lng": "-5.9000", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "126617", 
          "population_proper": "126617"
        }, 
        {"id":30,
          "city": "Larache", 
          "lat": "35.1833", 
          "lng": "-6.1500", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "125008", 
          "population_proper": "125008"
        }, 
        {"id":31,
          "city": "Guelmim", 
          "lat": "28.9833", 
          "lng": "-10.0667", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Guelmim-Oued Noun", 
          "capital": "admin", 
          "population": "118318", 
          "population_proper": "118318"
        }, 
        {"id":32,
          "city": "Khénifra", 
          "lat": "32.9300", 
          "lng": "-5.6600", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "117510", 
          "population_proper": "117510"
        }, 
        {"id":33,
          "city": "Berkane", 
          "lat": "34.9167", 
          "lng": "-2.3167", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Oriental", 
          "capital": "", 
          "population": "109237", 
          "population_proper": "109237"
        }, 
        {"id":1133,
          "city": "Bouskoura", 
          "lat": "33.4489", 
          "lng": "-7.6486", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "103026", 
          "population_proper": "103026"
        }, 
        {"id":34,
          "city": "Al Fqih Ben Çalah", 
          "lat": "32.5000", 
          "lng": "-6.7000", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "102019", 
          "population_proper": "102019"
        }, 
        {"id":35,
          "city": "Oued Zem", 
          "lat": "32.8600", 
          "lng": "-6.5600", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "95267", 
          "population_proper": "95267"
        }, 
        {"id":36,
          "city": "Sidi Slimane", 
          "lat": "34.2600", 
          "lng": "-5.9300", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "92989", 
          "population_proper": "92989"
        }, 
        {"id":37,
          "city": "Errachidia", 
          "lat": "31.9319", 
          "lng": "-4.4244", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Drâa-Tafilalet", 
          "capital": "admin", 
          "population": "92374", 
          "population_proper": "92374"
        }, 
        {"id":38,
          "city": "Guercif", 
          "lat": "34.2300", 
          "lng": "-3.3600", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Oriental", 
          "capital": "", 
          "population": "90880", 
          "population_proper": "90880"
        }, 
        {"id":39,
          "city": "Oulad Teïma", 
          "lat": "30.4000", 
          "lng": "-9.2100", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "", 
          "population": "89387", 
          "population_proper": "89387"
        }, 
        {"id":40,
          "city": "Ad Dakhla", 
          "lat": "23.7141", 
          "lng": "-15.9368", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "", 
          "capital": "", 
          "population": "89292", 
          "population_proper": "75000"
        }, 
        {"id":41,
          "city": "Ben Guerir", 
          "lat": "32.2300", 
          "lng": "-7.9500", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "88626", 
          "population_proper": "88626"
        }, 
        {"id":42,
          "city": "Wislane", 
          "lat": "30.2167", 
          "lng": "-8.3833", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "", 
          "population": "87910", 
          "population_proper": "87910"
        }, 
        {"id":43,
          "city": "Tiflet", 
          "lat": "33.9000", 
          "lng": "-6.3300", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "86709", 
          "population_proper": "86709"
        }, 
        {"id":44,
          "city": "Lqoliaa", 
          "lat": "30.2942", 
          "lng": "-9.4544", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "", 
          "population": "83235", 
          "population_proper": "83235"
        }, 
        {"id":45,
          "city": "Taroudannt", 
          "lat": "30.4711", 
          "lng": "-8.8778", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "", 
          "population": "80149", 
          "population_proper": "80149"
        }, 
        {"id":46,
          "city": "Sefrou", 
          "lat": "33.8300", 
          "lng": "-4.8300", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "79887", 
          "population_proper": "79887"
        }, 
        {"id":47,
          "city": "Essaouira", 
          "lat": "31.5130", 
          "lng": "-9.7687", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "77966", 
          "population_proper": "77966"
        }, 
        {"id":48,
          "city": "Fnidq", 
          "lat": "35.8500", 
          "lng": "-5.3500", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "77436", 
          "population_proper": "77436"
        }, 
        {"id":49,
          "city": "Ait Ali", 
          "lat": "30.1739", 
          "lng": "-9.4881", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "", 
          "population": "76646", 
          "population_proper": "76646"
        }, 
        {"id":50,
          "city": "Sidi Qacem", 
          "lat": "34.2100", 
          "lng": "-5.7000", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "75672", 
          "population_proper": "75672"
        }, 
        {"id":51,
          "city": "Tiznit", 
          "lat": "29.7000", 
          "lng": "-9.7269", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "", 
          "population": "74699", 
          "population_proper": "74699"
        }, 
        {"id":52,
          "city": "Moulay Abdallah", 
          "lat": "33.1978", 
          "lng": "-8.5883", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "74671", 
          "population_proper": "74671"
        }, 
        {"id":53,
          "city": "Tan-Tan", 
          "lat": "28.4333", 
          "lng": "-11.1000", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Guelmim-Oued Noun", 
          "capital": "", 
          "population": "73209", 
          "population_proper": "73209"
        }, 
        {"id":54,
          "city": "Warzat", 
          "lat": "30.9167", 
          "lng": "-6.9167", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Drâa-Tafilalet", 
          "capital": "", 
          "population": "71067", 
          "population_proper": "71067"
        }, 
        {"id":55,
          "city": "Youssoufia", 
          "lat": "32.2500", 
          "lng": "-8.5300", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "67628", 
          "population_proper": "67628"
        }, 
        {"id":56,
          "city": "Sa’ada", 
          "lat": "31.6258", 
          "lng": "-8.1028", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "67086", 
          "population_proper": "67086"
        }, 
        {"id":57,
          "city": "Martil", 
          "lat": "35.6100", 
          "lng": "-5.2700", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "64355", 
          "population_proper": "64355"
        }, 
        {"id":58,
          "city": "Aïn Harrouda", 
          "lat": "33.6372", 
          "lng": "-7.4483", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "62420", 
          "population_proper": "62420"
        }, 
        {"id":59,
          "city": "Skhirate", 
          "lat": "33.8500", 
          "lng": "-7.0300", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "59775", 
          "population_proper": "59775"
        }, 
        {"id":60,
          "city": "Ouezzane", 
          "lat": "34.8000", 
          "lng": "-5.6000", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "59606", 
          "population_proper": "59606"
        }, 
        {"id":61,
          "city": "Sidi Yahya Zaer", 
          "lat": "33.8261", 
          "lng": "-6.9039", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "57790", 
          "population_proper": "57790"
        }, 
        {"id":62,
          "city": "Benslimane", 
          "lat": "33.6122", 
          "lng": "-7.1211", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "57101", 
          "population_proper": "57101"
        }, 
        {"id":63,
          "city": "Al Hoceïma", 
          "lat": "35.2472", 
          "lng": "-3.9322", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "56716", 
          "population_proper": "56716"
        }, 
        {"id":64,
          "city": "Beni Enzar", 
          "lat": "35.2569", 
          "lng": "-2.9342", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Oriental", 
          "capital": "", 
          "population": "56582", 
          "population_proper": "56582"
        }, 
        {"id":65,
          "city": "M’diq", 
          "lat": "35.6857", 
          "lng": "-5.3251", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "56227", 
          "population_proper": "56227"
        }, 
        {"id":66,
          "city": "Sidi Bennour", 
          "lat": "32.6550", 
          "lng": "-8.4292", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "55815", 
          "population_proper": "55815"
        }, 
        {"id":67,
          "city": "Midalt", 
          "lat": "32.6800", 
          "lng": "-4.7400", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Drâa-Tafilalet", 
          "capital": "", 
          "population": "55304", 
          "population_proper": "55304"
        }, 
        {"id":68,
          "city": "Azrou", 
          "lat": "33.4300", 
          "lng": "-5.2100", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "54350", 
          "population_proper": "54350"
        }, 
        {"id":69,
          "city": "Ain El Aouda", 
          "lat": "33.8111", 
          "lng": "-6.7922", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "49816", 
          "population_proper": "49816"
        }, 
        {"id":70,
          "city": "Beni Yakhlef", 
          "lat": "33.6681", 
          "lng": "-7.2514", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "48338", 
          "population_proper": "48338"
        }, 
        {"id":71,
          "city": "Semara", 
          "lat": "26.7333", 
          "lng": "-11.6833", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "", 
          "capital": "", 
          "population": "48149", 
          "population_proper": "48149"
        }, 
        {"id":72,
          "city": "Ad Darwa", 
          "lat": "33.4167", 
          "lng": "-7.5333", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "47719", 
          "population_proper": "47719"
        }, 
        {"id":73,
          "city": "Al Aaroui", 
          "lat": "35.0104", 
          "lng": "-3.0073", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Oriental", 
          "capital": "", 
          "population": "47599", 
          "population_proper": "47599"
        }, 
        {"id":74,
          "city": "Qasbat Tadla", 
          "lat": "32.6000", 
          "lng": "-6.2600", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "47343", 
          "population_proper": "47343"
        }, 
        {"id":75,
          "city": "Boujad", 
          "lat": "32.7600", 
          "lng": "-6.4000", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "46893", 
          "population_proper": "46893"
        }, 
        {"id":76,
          "city": "Jerada", 
          "lat": "34.3100", 
          "lng": "-2.1600", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Oriental", 
          "capital": "", 
          "population": "43506", 
          "population_proper": "43506"
        }, 
        {"id":77,
          "city": "Chefchaouene", 
          "lat": "35.1714", 
          "lng": "-5.2697", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "42786", 
          "population_proper": "42786"
        }, 
        {"id":78,
          "city": "Mrirt", 
          "lat": "33.1667", 
          "lng": "-5.5667", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "42730", 
          "population_proper": "42730"
        }, 
        {"id":79,
          "city": "Sidi Mohamed Lahmar", 
          "lat": "34.7167", 
          "lng": "-6.2667", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "42637", 
          "population_proper": "42637"
        }, 
        {"id":80,
          "city": "Tineghir", 
          "lat": "31.5147", 
          "lng": "-5.5328", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Drâa-Tafilalet", 
          "capital": "", 
          "population": "42044", 
          "population_proper": "42044"
        }, 
        {"id":81,
          "city": "El Aïoun", 
          "lat": "34.5853", 
          "lng": "-2.5056", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Oriental", 
          "capital": "", 
          "population": "41832", 
          "population_proper": "41832"
        }, 
        {"id":82,
          "city": "Azemmour", 
          "lat": "33.2833", 
          "lng": "-8.3333", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "40920", 
          "population_proper": "40920"
        }, 
        {"id":83,
          "city": "Temsia", 
          "lat": "30.3633", 
          "lng": "-9.4144", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "", 
          "population": "40780", 
          "population_proper": "40780"
        }, 
        {"id":84,
          "city": "Zoumi", 
          "lat": "34.8032", 
          "lng": "-5.3446", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "40661", 
          "population_proper": "40661"
        }, 
        {"id":85,
          "city": "Laouamra", 
          "lat": "35.0656", 
          "lng": "-6.0939", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "40605", 
          "population_proper": "40605"
        }, 
        {"id":86,
          "city": "Zagora", 
          "lat": "30.3316", 
          "lng": "-5.8376", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Drâa-Tafilalet", 
          "capital": "", 
          "population": "40067", 
          "population_proper": "40067"
        }, 
        {"id":87,
          "city": "Ait Ourir", 
          "lat": "31.5644", 
          "lng": "-7.6628", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "39108", 
          "population_proper": "39108"
        }, 
        {"id":88,
          "city": "Sidi Bibi", 
          "lat": "30.2333", 
          "lng": "-9.5333", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "", 
          "population": "39042", 
          "population_proper": "39042"
        }, 
        {"id":89,
          "city": "Aziylal", 
          "lat": "31.9600", 
          "lng": "-6.5600", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "38520", 
          "population_proper": "38520"
        }, 
        {"id":90,
          "city": "Sidi Yahia El Gharb", 
          "lat": "34.3058", 
          "lng": "-6.3058", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "37979", 
          "population_proper": "37979"
        }, 
        {"id":91,
          "city": "Biougra", 
          "lat": "30.2144", 
          "lng": "-9.3708", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "", 
          "population": "37933", 
          "population_proper": "37933"
        }, 
        {"id":92,
          "city": "Taounate", 
          "lat": "34.5358", 
          "lng": "-4.6400", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "37616", 
          "population_proper": "37616"
        }, 
        {"id":93,
          "city": "Bouznika", 
          "lat": "33.7894", 
          "lng": "-7.1597", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "37238", 
          "population_proper": "37238"
        }, 
        {"id":94,
          "city": "Aourir", 
          "lat": "30.4833", 
          "lng": "-9.6333", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "", 
          "population": "36948", 
          "population_proper": "36948"
        }, 
        {"id":95,
          "city": "Zaïo", 
          "lat": "34.9396", 
          "lng": "-2.7334", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Oriental", 
          "capital": "", 
          "population": "35806", 
          "population_proper": "35806"
        }, 
        {"id":96,
          "city": "Aguelmous", 
          "lat": "33.1500", 
          "lng": "-5.8333", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "35626", 
          "population_proper": "35626"
        }, 
        {"id":97,
          "city": "El Hajeb", 
          "lat": "33.6928", 
          "lng": "-5.3711", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "35282", 
          "population_proper": "35282"
        }, 
        {"id":98,
          "city": "Mnasra", 
          "lat": "34.7667", 
          "lng": "-5.5167", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "34429", 
          "population_proper": "34429"
        }, 
        {"id":99,
          "city": "Mediouna", 
          "lat": "33.4500", 
          "lng": "-7.5100", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "34250", 
          "population_proper": "34250"
        }, 
        {"id":100,
          "city": "Zeghanghane", 
          "lat": "35.1575", 
          "lng": "-3.0017", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Oriental", 
          "capital": "", 
          "population": "34025", 
          "population_proper": "34025"
        }, 
        {"id":101,
          "city": "Imzouren", 
          "lat": "35.1448", 
          "lng": "-3.8505", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "33852", 
          "population_proper": "33852"
        }, 
        {"id":102,
          "city": "Loudaya", 
          "lat": "31.6507", 
          "lng": "-8.3021", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "33767", 
          "population_proper": "33767"
        }, 
        {"id":103,
          "city": "Oulad Zemam", 
          "lat": "32.3500", 
          "lng": "-6.6333", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "33652", 
          "population_proper": "33652"
        }, 
        {"id":1031,
          "city": "Bou Ahmed", 
          "lat": "33.1119", 
          "lng": "-7.4058", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "33105", 
          "population_proper": "33105"
        }, 
        {"id":104,
          "city": "Tit Mellil", 
          "lat": "33.5581", 
          "lng": "-7.4858", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "32782", 
          "population_proper": "32782"
        }, 
        {"id":105,
          "city": "Arbaoua", 
          "lat": "34.9000", 
          "lng": "-5.9167", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "32690", 
          "population_proper": "32690"
        }, 
        {"id":106,
          "city": "Douar Oulad Hssine", 
          "lat": "33.0681", 
          "lng": "-8.5108", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "32130", 
          "population_proper": "32130"
        }, 
        {"id":107,
          "city": "Bahharet Oulad Ayyad", 
          "lat": "34.7703", 
          "lng": "-6.3047", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "31860", 
          "population_proper": "31860"
        }, 
        {"id":108,
          "city": "Mechraa Bel Ksiri", 
          "lat": "34.5787", 
          "lng": "-5.9630", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "31497", 
          "population_proper": "31497"
        }, 
        {"id":109,
          "city": "Mograne", 
          "lat": "34.4167", 
          "lng": "-6.4333", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "31292", 
          "population_proper": "31292"
        }, 
        {"id":110,
          "city": "Dar Ould Zidouh", 
          "lat": "32.3167", 
          "lng": "-6.9000", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "31170", 
          "population_proper": "31170"
        }, 
        {"id":111,
          "city": "Asilah", 
          "lat": "35.4667", 
          "lng": "-6.0333", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "31147", 
          "population_proper": "31147"
        }, 
        {"id":112,
          "city": "Demnat", 
          "lat": "31.7311", 
          "lng": "-7.0361", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "29504", 
          "population_proper": "29504"
        }, 
        {"id":113,
          "city": "Lalla Mimouna", 
          "lat": "34.8500", 
          "lng": "-6.0669", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "29479", 
          "population_proper": "29479"
        }, 
        {"id":114,
          "city": "Fritissa", 
          "lat": "33.6167", 
          "lng": "-3.5500", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "29460", 
          "population_proper": "29460"
        }, 
        {"id":115,
          "city": "Arfoud", 
          "lat": "31.4361", 
          "lng": "-4.2328", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Drâa-Tafilalet", 
          "capital": "", 
          "population": "29279", 
          "population_proper": "29279"
        }, 
        {"id":116,
          "city": "Tameslouht", 
          "lat": "31.5000", 
          "lng": "-8.1000", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "28978", 
          "population_proper": "28978"
        }, 
        {"id":1161,
          "city": "Bou Arfa", 
          "lat": "32.5310", 
          "lng": "-1.9631", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Oriental", 
          "capital": "", 
          "population": "28846", 
          "population_proper": "28846"
        }, 
        {"id":117,
          "city": "Sidi Smai’il", 
          "lat": "32.8167", 
          "lng": "-8.5000", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "28733", 
          "population_proper": "28733"
        }, 
        {"id":118,
          "city": "Taza", 
          "lat": "35.0639", 
          "lng": "-5.2025", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "28713", 
          "population_proper": "28713"
        }, 
        {"id":119,
          "city": "Souk et Tnine Jorf el Mellah", 
          "lat": "34.4833", 
          "lng": "-5.5169", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "28681", 
          "population_proper": "28681"
        }, 
        {"id":120,
          "city": "Mehdya", 
          "lat": "34.2557", 
          "lng": "-6.6745", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "28636", 
          "population_proper": "28636"
        }, 
        {"id":121,
          "city": "Oulad Hammou", 
          "lat": "33.2500", 
          "lng": "-8.3347", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "28449", 
          "population_proper": "28449"
        }, 
        {"id":122,
          "city": "Douar Oulad Aj-jabri", 
          "lat": "32.2567", 
          "lng": "-6.7839", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "28438", 
          "population_proper": "28438"
        }, 
        {"id":123,
          "city": "Aïn Taoujdat", 
          "lat": "33.9333", 
          "lng": "-5.2167", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "28288", 
          "population_proper": "28288"
        }, 
        {"id":124,
          "city": "Dar Bel Hamri", 
          "lat": "34.1889", 
          "lng": "-5.9697", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "28156", 
          "population_proper": "28156"
        }, 
        {"id":125,
          "city": "Chichaoua", 
          "lat": "31.5333", 
          "lng": "-8.7667", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "27869", 
          "population_proper": "27869"
        }, 
        {"id":126,
          "city": "Tahla", 
          "lat": "34.0476", 
          "lng": "-4.4289", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "27729", 
          "population_proper": "27729"
        }, 
        {"id":127,
          "city": "Bellaa", 
          "lat": "30.0314", 
          "lng": "-9.5542", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "", 
          "population": "27699", 
          "population_proper": "27699"
        }, 
        {"id":128,
          "city": "Oulad Yaïch", 
          "lat": "32.4167", 
          "lng": "-6.3333", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "27476", 
          "population_proper": "27476"
        }, 
        {"id":129,
          "city": "Ksebia", 
          "lat": "34.2933", 
          "lng": "-6.1594", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "27059", 
          "population_proper": "27059"
        }, 
        {"id":130,
          "city": "Tamorot", 
          "lat": "34.9333", 
          "lng": "-4.7833", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "26748", 
          "population_proper": "26748"
        }, 
        {"id":131,
          "city": "Moulay Bousselham", 
          "lat": "34.8786", 
          "lng": "-6.2933", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "26608", 
          "population_proper": "26608"
        }, 
        {"id":132,
          "city": "Sabaa Aiyoun", 
          "lat": "33.8969", 
          "lng": "-5.3611", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "26277", 
          "population_proper": "26277"
        }, 
        {"id":133,
          "city": "Bourdoud", 
          "lat": "34.5922", 
          "lng": "-4.5492", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "26236", 
          "population_proper": "26236"
        }, 
        {"id":134,
          "city": "Aït Faska", 
          "lat": "31.5058", 
          "lng": "-7.7161", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "26210", 
          "population_proper": "26210"
        }, 
        {"id":135,
          "city": "Boureït", 
          "lat": "34.9833", 
          "lng": "-4.9167", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "25872", 
          "population_proper": "25872"
        }, 
        {"id":136,
          "city": "Lamzoudia", 
          "lat": "31.5833", 
          "lng": "-8.4833", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "25674", 
          "population_proper": "25674"
        }, 
        {"id":137,
          "city": "Oulad Said", 
          "lat": "32.6320", 
          "lng": "-8.8456", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "25650", 
          "population_proper": "25650"
        }, 
        {"id":138,
          "city": "Missour", 
          "lat": "33.0500", 
          "lng": "-3.9908", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "25584", 
          "population_proper": "25584"
        }, 
        {"id":139,
          "city": "Ain Aicha", 
          "lat": "34.4833", 
          "lng": "-4.7000", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "25417", 
          "population_proper": "25417"
        }, 
        {"id":140,
          "city": "Zawyat ech Cheïkh", 
          "lat": "32.6541", 
          "lng": "-5.9214", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "25388", 
          "population_proper": "25388"
        }, 
        {"id":141,
          "city": "Bouknadel", 
          "lat": "34.1245", 
          "lng": "-6.7480", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "25255", 
          "population_proper": "25255"
        }, 
        {"id":142,
          "city": "El Ghiate", 
          "lat": "32.0331", 
          "lng": "-9.1625", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "25162", 
          "population_proper": "25162"
        }, 
        {"id":143,
          "city": "Safsaf", 
          "lat": "34.5581", 
          "lng": "-6.0078", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "25075", 
          "population_proper": "25075"
        }, 
        {"id":144,
          "city": "Ouaoula", 
          "lat": "31.8667", 
          "lng": "-6.7500", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "24790", 
          "population_proper": "24790"
        }, 
        {"id":145,
          "city": "Douar Olad. Salem", 
          "lat": "32.8739", 
          "lng": "-8.8589", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "24775", 
          "population_proper": "24775"
        }, 
        {"id":146,
          "city": "Oulad Tayeb", 
          "lat": "33.9598", 
          "lng": "-4.9954", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "24594", 
          "population_proper": "24594"
        }, 
        {"id":147,
          "city": "Echemmaia Est", 
          "lat": "32.0705", 
          "lng": "-8.6532", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "24303", 
          "population_proper": "24303"
        }, 
        {"id":148,
          "city": "Oulad Barhil", 
          "lat": "30.6388", 
          "lng": "-8.4732", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "", 
          "population": "24288", 
          "population_proper": "24288"
        }, 
        {"id":149,
          "city": "Douar ’Ayn Dfali", 
          "lat": "33.9500", 
          "lng": "-4.4500", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "24241", 
          "population_proper": "24241"
        }, 
        {"id":150,
          "city": "Setti Fatma", 
          "lat": "31.2256", 
          "lng": "-7.6758", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "24129", 
          "population_proper": "24129"
        }, 
        {"id":151,
          "city": "Skoura", 
          "lat": "31.0672", 
          "lng": "-6.5397", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Drâa-Tafilalet", 
          "capital": "", 
          "population": "24055", 
          "population_proper": "24055"
        }, 
        {"id":152,
          "city": "Douar Ouled Ayad", 
          "lat": "32.4167", 
          "lng": "-7.1000", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "23818", 
          "population_proper": "23818"
        }, 
        {"id":153,
          "city": "Zawyat an Nwaçer", 
          "lat": "33.3611", 
          "lng": "-7.6114", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Casablanca-Settat", 
          "capital": "", 
          "population": "23802", 
          "population_proper": "23802"
        }, 
        {"id":154,
          "city": "Khenichet-sur Ouerrha", 
          "lat": "34.4383", 
          "lng": "-5.6844", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Rabat-Salé-Kénitra", 
          "capital": "", 
          "population": "23707", 
          "population_proper": "23707"
        }, 
        {"id":155,
          "city": "Ayt Mohamed", 
          "lat": "32.5667", 
          "lng": "-6.9833", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Béni Mellal-Khénifra", 
          "capital": "", 
          "population": "23696", 
          "population_proper": "23696"
        }, 
        {"id":156,
          "city": "Gueznaia", 
          "lat": "35.7200", 
          "lng": "-5.8940", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Tanger-Tétouan-Al Hoceïma", 
          "capital": "", 
          "population": "23601", 
          "population_proper": "23601"
        }, 
        {"id":157,
          "city": "Oulad Hassoune", 
          "lat": "31.6503", 
          "lng": "-7.8361", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Marrakech-Safi", 
          "capital": "", 
          "population": "23475", 
          "population_proper": "23475"
        }, 
        {"id":158,
          "city": "Bni Frassen", 
          "lat": "34.3819", 
          "lng": "-4.3761", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Fès-Meknès", 
          "capital": "", 
          "population": "23429", 
          "population_proper": "23429"
        }, 
        {"id":159,
          "city": "Tifariti", 
          "lat": "26.0928", 
          "lng": "-10.6089", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "", 
          "capital": "primary", 
          "population": "", 
          "population_proper": ""
        }, 
        {"id":160,
          "city": "Zawit Al Bour", 
          "lat": "30.6748", 
          "lng": "-8.1742", 
          "country": "Morocco", 
          "iso2": "MA", 
          "admin_name": "Souss-Massa", 
          "capital": "minor", 
          "population": "", 
          "population_proper": ""
        }
      ];
export default Citys
